
--出品大类表
DROP TABLE
    C_T_FOOD_BIGCLS;
CREATE TABLE
    C_T_FOOD_BIGCLS
    (
        CBIGCLS_C VARCHAR(4) NOT NULL,
        CBIGCLS_N VARCHAR(30) NOT NULL,
        SAREA VARCHAR(20) NOT NULL,
        CBRANCH_C VARCHAR(4) NOT NULL,
        CONSTRAINT C_T_FOOD_BIGCLS PRIMARY KEY (CBIGCLS_C)
    );
--出品小类表
DROP TABLE
    C_T_FOOD_LITCLS;
CREATE TABLE
    C_T_FOOD_LITCLS
    (
        CLITCLS_C VARCHAR(4) NOT NULL,
        CLITCLS_N VARCHAR(30) NOT NULL,
        BLIMIT NUMBER(1) NOT NULL,
        BSERVICEFEE NUMBER(1) NOT NULL,
        BDISCOUNT NUMBER(1) NOT NULL,
        CBIGCLS_C VARCHAR(4) NOT NULL,
        CBIGCLS_N VARCHAR(30) NOT NULL,
        BPRINTLABEL NUMBER(1),
        ICOLORINDEX NUMBER(10),
        BILL_DISPLAY CHAR(1),
        CBRANCH_C VARCHAR(4),
        TABLEBILL_DISPLAY VARCHAR(5),
        CONSTRAINT C_T_FOOD_LITCLS_PK PRIMARY KEY (CLITCLS_C)
    );

--出品表
DROP TABLE
    C_T_FOOD;
CREATE TABLE
    C_T_FOOD
    (
        CFOOD_C VARCHAR(12) NOT NULL,
        CFOOD_N VARCHAR(70) NOT NULL,
        CNAMEENG VARCHAR(80),
        SUNIT VARCHAR(12) NOT NULL,
        SNAMEFAST VARCHAR(70),
        CLITCLS_C VARCHAR(4) NOT NULL,
        CLITCLS_N VARCHAR(30) NOT NULL,
        NPRC NUMBER(12,4) NOT NULL,
        NPRCROOM NUMBER(12,4) NOT NULL,
        NPRCOUT NUMBER(12,4) NOT NULL,
        NFEE NUMBER(12,4) NOT NULL,
        NDEDUCT NUMBER(12,4) NOT NULL,
        NCOST NUMBER(12,4) NOT NULL,
        BHANDFOOD NUMBER(1) NOT NULL,
        BPRCMOD NUMBER(1) NOT NULL,
        BQTYMOD NUMBER(1) NOT NULL,
        BMADMETHOD NUMBER(1) NOT NULL,
        BSUITFOOD NUMBER(1) NOT NULL,
        BUSE NUMBER(1) NOT NULL,
        BMULTIUNIT NUMBER(1) NOT NULL,
        BSALECLOSE NUMBER(1) NOT NULL,
        BVOUCH NUMBER(1) NOT NULL,
        BTIMEPRC NUMBER(1) NOT NULL,
        BSPLITPRINT NUMBER(1) NOT NULL,
        ESUITTYPE VARCHAR(24) NOT NULL,
        SPRINTER VARCHAR(24) NOT NULL,
        SDESC VARCHAR(256) NOT NULL,
        SPICNAME VARCHAR(64) NOT NULL,
        MPIC BLOB,
        CMADEDESC varchar(4000),
        EFOODTYPE VARCHAR(12),
        INUM NUMBER(10),
        NPRCVIP1 NUMBER(12,4),
        NPRCVIP2 NUMBER(12,4),
        NPRCVIP3 NUMBER(12,4),
        BLIMIT NUMBER(10),
        BSERVICEFEE NUMBER(10),
        BDISCOUNT NUMBER(10),
        BINPUTNUM NUMBER(1) DEFAULT 0,
        BINPUTSIZE NUMBER(1) DEFAULT 0,
        BSERVICEMAN NUMBER(1) DEFAULT 0 NOT NULL,
        CSECOND_C VARCHAR(20),
        BCUSTOMFOOD NUMBER(1) DEFAULT 0,
        SCRAFTREMARK VARCHAR(256),
        SFOODSMELL VARCHAR(64),
        SFOODTASTE VARCHAR(64),
        BPULLCOMPUTE NUMBER(3) DEFAULT 0,
        IWARNING_1 NUMBER(10),
        IWARNING_2 NUMBER(10),
        BSETWEIGHT NUMBER(1) DEFAULT 0,
        NPRCROOM2 NUMBER(12,4),
        NPRCROOM3 NUMBER(12,4),
        NPRCROOM4 NUMBER(12,4),
        CBRPRICEFLAG CHAR(10),
        BUNTICKETPAY NUMBER(1),
        NDEDUCTPER NUMBER(12,4),
        NLOWESTDISCUR NUMBER(12,4),
        SBIGPICNAME VARCHAR(64),
        MBIGPIC BLOB,
        CBRANCH_C VARCHAR(4),
        BDIS_FOOD NUMBER(10),
        ISALETYPE NUMBER(10),
        BSALEPROMOTION NUMBER(1),
        BTIMEFEE NUMBER(1),
        ICLOCKTIME NUMBER(10),
        ITIMEFEETYPE NUMBER(10),
        ITIMEFEECRSTIME NUMBER(10),
        ITIMECRSAVGTIME NUMBER(10),
        ITIMECRSAVGAMT NUMBER(10),
        BTICKET NUMBER(1),
        BINHANDPRO NUMBER(1),
        BBANQUET_SUIT NUMBER(1),
        CBIGCLS_N VARCHAR(30),
        BINPAD NUMBER(1)
    );